# Generated by Django 6.0.7 on 2026-07-23 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('resource_type', models.CharField(choices=[('Hospital', 'Hospital'), ('Ambulance', 'Ambulance'), ('Police', 'Police'), ('Relief Camp', 'Relief Camp'), ('Fire Station', 'Fire Station')], max_length=50)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('availability', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disaster_type', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('alert_message', models.TextField()),
                ('alert_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HelpRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=200)),
                ('emergency_type', models.CharField(choices=[('Flood', 'Flood'), ('Fire', 'Fire'), ('Earthquake', 'Earthquake'), ('Cyclone', 'Cyclone'), ('Landslide', 'Landslide'), ('Tsunami', 'Tsunami'), ('Medical', 'Medical Emergency'), ('Other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Received', 'Received'), ('In Process', 'In Process'), ('Completed', 'Completed')], default='Received', max_length=30)),
                ('response_result', models.TextField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('role', models.CharField(choices=[('USER', 'User'), ('COORDINATOR', 'Emergency Coordinator')], default='USER', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
